### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by luckypoem** [Jamesits/myip#1]
hi.

yudeMacBook-Air:gopath brite$ go get -u -v github.com/Jamesits/myip/src/
github.com/Jamesits/myip (download)
github.com/gortc/stun (download)
get "gortc.io/stun/v2/internal/hmac": found meta tag get.metaImport{Prefix:"gortc.io/stun", VCS:"git", RepoRoot:"https://github.com/gortc/stun"} at //gortc.io/stun/v2/internal/hmac?go-get=1
get "gortc.io/stun/v2/internal/hmac": verifying non-authoritative meta tag
gortc.io/stun (download)
src/github.com/gortc/stun/checks.go:5:8: use of internal package gortc.io/stun/internal/hmac not allowed
yudeMacBook-Air:gopath brite$

怎么解决？

**Comment by Jamesits** [comment]
请用 https://github.com/Jamesits/myip/blob/master/build.sh 编译。

不打算支持 `go get` 编译方法了，`GOPATH` 这套东西实在太垃圾，我不接受。如果你实在有这个需求的话可以帮我做一下支持。
